try:
	‘’’bruh
except Exception as e:
	print(e)